# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_image', models.ImageField(upload_to='pic/')),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
    ]
