# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20191018_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
