# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 10:51
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20191018_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=tinymce.models.HTMLField(),
        ),
    ]
